import Foundation

/// A repository the owner works in, found by looking inside the folders they chose.
///
/// There used to be a second way in: a markdown table at `~/Projects/INDEX.md`, generated by a
/// script. It was one person's habit, and building on it meant everybody else opened the app to no
/// projects and no explanation — and meant a Settings screen that had to describe a file most
/// people should never hear about. One source now, and it is the one anybody can answer:
/// which folders hold your repositories. See `ProjectRoots`.
public enum Projects {}
