import Foundation

/// The folders Loadout looks in for repositories, and the search itself.
///
/// Until now the project list came from one file — `~/Projects/INDEX.md`, a markdown table
/// generated by a script its author happens to run. Anyone without that file saw no projects at
/// all, however many repositories they had and wherever they kept them. That is not a setting
/// being wrong; it is a personal habit standing in for a feature.
///
/// So the app now keeps the short, stable thing — *where to look*, two or three folders somebody
/// types once — and works out the long, changing thing for itself: which repositories are in
/// there today. A repository created this morning is in the list this afternoon, with nobody
/// maintaining anything.
public struct ProjectRoots: Sendable {
    /// Where the chosen folders are remembered. Paths are stored with the home folder written as
    /// `~`, so a list still makes sense if the account is ever renamed.
    public static let defaultsKey = "projectRoots"

    /// How deep under a chosen folder a repository can sit and still be found.
    ///
    /// Three levels, because two was not enough for a real machine: repositories turned up at
    /// `~/Projects/PERSONAL/APPS/loadout`, and a limit of two found none of them while reporting
    /// success. It stops descending the moment it finds a repository, so the cost is in empty
    /// scaffolding folders rather than in anybody's source tree.
    public static let searchDepth = 3

    /// The folders to search, in the order they were added.
    public var folders: [URL]

    public init(folders: [URL]) {
        self.folders = folders
    }

    // MARK: - Remembering the choice

    public static func load(
        defaults: UserDefaults = .standard, home: URL = FileManager.default.homeDirectoryForCurrentUser
    ) -> ProjectRoots {
        // A fixture home says its own folders, and says them completely: the real account's
        // choice must not leak into a run pointed somewhere else, or a self-check starts finding
        // whatever the person at this keyboard happens to work on.
        if let fixture = ProcessInfo.processInfo.environment["LOADOUT_HOME"], !fixture.isEmpty {
            let listed = ProcessInfo.processInfo.environment["LOADOUT_PROJECT_ROOTS"] ?? ""
            return ProjectRoots(
                folders: listed.split(separator: ":").map { expand(String($0), home: home) }
            )
        }
        let stored = defaults.stringArray(forKey: defaultsKey) ?? []
        return ProjectRoots(folders: stored.map { expand($0, home: home) })
    }

    public func save(
        to defaults: UserDefaults = .standard, home: URL = FileManager.default.homeDirectoryForCurrentUser
    ) {
        // A run pointed at a fixture home reads its folders from the environment and must not write
        // back: the preferences it would write are the real account's, so a screenshot script or a
        // walkthrough would replace the folders somebody actually chose with the fixture's.
        guard (ProcessInfo.processInfo.environment["LOADOUT_HOME"] ?? "").isEmpty else { return }
        defaults.set(folders.map { Self.abbreviate($0, home: home) }, forKey: Self.defaultsKey)
    }

    static func expand(_ path: String, home: URL) -> URL {
        guard path.hasPrefix("~") else { return URL(fileURLWithPath: path) }
        return URL(fileURLWithPath: home.path + String(path.dropFirst()))
    }

    public static func abbreviate(_ url: URL, home: URL) -> String {
        let path = url.standardizedFileURL.path
        guard path == home.path || path.hasPrefix(home.path + "/") else { return path }
        return "~" + path.dropFirst(home.path.count)
    }

    // MARK: - Guessing, for somebody who has chosen nothing yet

    /// The folders people keep code in, offered on first run so the answer is a confirmation
    /// rather than a blank field. Only the ones that exist and actually hold a repository are
    /// returned — suggesting an empty `~/Developer` teaches somebody the app is guessing.
    public static func likelyFolders(
        home: URL = FileManager.default.homeDirectoryForCurrentUser
    ) -> [URL] {
        ["Projects", "Developer", "Code", "code", "src", "dev", "work", "repos", "git"]
            .map { home.appendingPathComponent($0) }
            .filter { isDirectory($0) && !repositories(under: $0).isEmpty }
    }

    // MARK: - The search

    /// Every repository under the chosen folders, sorted by the name it is shown under, with any
    /// one repository appearing once however many chosen folders contain it.
    public func discover(home: URL = FileManager.default.homeDirectoryForCurrentUser) -> [Project] {
        var seen = Set<String>()
        var found: [Project] = []
        for folder in folders {
            for url in Self.repositories(under: folder) {
                let standardized = url.standardizedFileURL
                guard seen.insert(standardized.path).inserted else { continue }
                found.append(Project(
                    name: standardized.lastPathComponent,
                    relativePath: Self.label(for: standardized, under: folder, home: home),
                    path: standardized
                ))
            }
        }
        return found.sorted { $0.relativePath.lowercased() < $1.relativePath.lowercased() }
    }

    /// What a project is called in the list: its path below the chosen folder, so two repositories
    /// named `site` in different clients read as `nova/site` and `acme/site` rather than as the
    /// same thing twice.
    static func label(for url: URL, under folder: URL, home: URL) -> String {
        let base = folder.standardizedFileURL.path
        let path = url.standardizedFileURL.path
        if path.hasPrefix(base + "/") { return String(path.dropFirst(base.count + 1)) }
        return abbreviate(url, home: home)
    }

    /// Walks a folder looking for repositories, stopping as soon as it finds one on a branch.
    ///
    /// A folder counts as a repository when it holds a `.git` — the usual answer — or a `.claude`,
    /// which catches a checkout somebody keeps outside git but still configures for an assistant.
    /// Hidden folders are skipped, which keeps this out of `.git` internals, and `node_modules` is
    /// skipped by name because it is deep, enormous, and never a project of yours.
    ///
    /// The folder somebody *chose* is never itself the answer, even when it looks like a
    /// repository. A real `~/Projects` had a `.claude` of its own — house instructions for the
    /// whole tree — and the search stopped dead on it and reported one project where there were
    /// ninety. What you point at is a place to look inside; only something nested can be the thing
    /// found.
    static func repositories(under folder: URL, depth: Int = searchDepth, isRoot: Bool = true) -> [URL] {
        guard depth >= 0, isDirectory(folder) else { return [] }
        if !isRoot, isRepository(folder) { return [folder] }
        guard depth > 0 else { return [] }

        let fm = FileManager.default
        guard let children = try? fm.contentsOfDirectory(
            at: folder, includingPropertiesForKeys: [.isDirectoryKey], options: [.skipsHiddenFiles]
        ) else { return [] }

        return children
            .filter { isDirectory($0) && $0.lastPathComponent != "node_modules" }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
            .flatMap { repositories(under: $0, depth: depth - 1, isRoot: false) }
    }

    static func isRepository(_ folder: URL) -> Bool {
        isDirectory(folder.appendingPathComponent(".git"))
            || FileManager.default.fileExists(atPath: folder.appendingPathComponent(".git").path)
            || isDirectory(folder.appendingPathComponent(".claude"))
    }

    static func isDirectory(_ url: URL) -> Bool {
        var isDirectory: ObjCBool = false
        let exists = FileManager.default.fileExists(atPath: url.path, isDirectory: &isDirectory)
        return exists && isDirectory.boolValue
    }
}
